enum AuthErrorCodes {
    INVALID_PASSWORD = 'INVALID_PASSWORD',
    USER_NOT_FOUND = 'USER_NOT_FOUND',
    USER_CREATION_FAILED = 'USER_CREATION_FAILED',
    NOT_AUTHORIZED = 'NOT_AUTHORIZED',
}

export { AuthErrorCodes };
